//! C / C++ build output detection.

use crate::analysis::context::{DirContext, Markers};
use crate::analysis::domain::{Category, CleanupSafety, Confidence, Detection, Technology};
use crate::analysis::engine::{Detector, Trigger};

use super::{SPEC_CONTEXT, SPEC_STRONG, SPEC_WEAK};

/// CMake's own scratch directories, which are unambiguous wherever they appear.
pub struct CMakeOutput;

// Triggers match a single path component, so they never contain a separator.
static CMAKE_TRIGGERS: &[Trigger] = &[
    Trigger::Name("cmakefiles"),
    Trigger::Prefix("cmake-build-"),
    Trigger::Name(".ccache"),
];

impl Detector for CMakeOutput {
    fn id(&self) -> &'static str {
        "cpp.cmake"
    }

    fn triggers(&self) -> &'static [Trigger] {
        CMAKE_TRIGGERS
    }

    fn detect(&self, ctx: &DirContext<'_>) -> Option<Detection> {
        if ctx.name_lower == ".ccache" {
            return Some(
                Detection::new(
                    Category::Cache,
                    Confidence::High,
                    CleanupSafety::Safe,
                    "ccache compiler cache",
                )
                .with_technology(Technology::Cpp)
                .with_evidence("Speeds up recompilation; rebuilt transparently.")
                .regenerated_by("ccache -C")
                .collapsed()
                .with_specificity(SPEC_STRONG),
            );
        }

        if ctx.name_lower.starts_with("cmake-build-") {
            return Some(
                Detection::new(
                    Category::BuildArtifact,
                    Confidence::High,
                    CleanupSafety::Safe,
                    "CLion CMake build directory",
                )
                .with_technology(Technology::CMake)
                .with_evidence(
                    "CLion creates `cmake-build-<profile>` directories and regenerates them \
                     whenever the profile is rebuilt.",
                )
                .regenerated_by("cmake --build .")
                .collapsed()
                .with_specificity(SPEC_STRONG),
            );
        }

        // `CMakeFiles` only ever appears inside a CMake build tree.
        Some(
            Detection::new(
                Category::BuildArtifact,
                Confidence::High,
                CleanupSafety::Safe,
                "CMake internal build files",
            )
            .with_technology(Technology::CMake)
            .with_evidence("Generated by `cmake` when configuring a build tree.")
            .regenerated_by("cmake ..")
            .collapsed()
            .with_specificity(SPEC_STRONG),
        )
    }
}

/// `build/` next to a native build script.
///
/// Deliberately conservative: reconfiguring a native build tree can be slow and
/// can require flags the user no longer remembers, so this never reports
/// [`CleanupSafety::Safe`].
pub struct NativeBuildDir;

static NATIVE_TRIGGERS: &[Trigger] = &[
    Trigger::Name("build"),
    Trigger::Name("builddir"),
    Trigger::Name("_build"),
];

impl Detector for NativeBuildDir {
    fn id(&self) -> &'static str {
        "cpp.build_dir"
    }

    fn triggers(&self) -> &'static [Trigger] {
        NATIVE_TRIGGERS
    }

    fn detect(&self, ctx: &DirContext<'_>) -> Option<Detection> {
        if !ctx.parent_is_project(Markers::NATIVE_PROJECT) {
            return None;
        }
        // Elixir also uses `_build`; that rule lives in `native_pkg` and carries
        // stronger evidence, so bail out when a `mix.exs` is present.
        if ctx.parent_is_project(Markers::MIX_EXS) {
            return None;
        }

        // A bare `Makefile` is weak evidence. Plenty of Python, JavaScript and
        // JVM projects keep one purely for `make test`, and calling their
        // `build/` directory "a native build tree" would be a confidently wrong
        // explanation. When a stronger project fingerprint is present, defer.
        let real_build_system = ctx
            .parent_markers
            .intersects(Markers::CMAKELISTS | Markers::MESON_BUILD | Markers::AUTOCONF);
        if !real_build_system
            && ctx.parent_markers.intersects(
                Markers::PY_PROJECT
                    .union(Markers::JS_PROJECT)
                    .union(Markers::JVM_PROJECT),
            )
        {
            return None;
        }

        let generator = if ctx.parent_markers.contains(Markers::CMAKELISTS) {
            ("CMake", "cmake --build build")
        } else if ctx.parent_markers.contains(Markers::MESON_BUILD) {
            ("Meson", "meson compile -C build")
        } else if ctx.parent_markers.contains(Markers::AUTOCONF) {
            ("configure", "make")
        } else {
            ("Make", "make")
        };

        Some(
            Detection::new(
                Category::BuildArtifact,
                if real_build_system {
                    Confidence::Medium
                } else {
                    Confidence::Low
                },
                CleanupSafety::ProbablySafe,
                "Native build directory",
            )
            .with_technology(Technology::Cpp)
            .with_evidence(format!(
                "A {} build script exists in the parent directory.",
                generator.0
            ))
            .with_evidence(
                "Reconfiguring a native build tree can be slow and may need the original \
                 configure flags, so this is not treated as automatically safe.",
            )
            .regenerated_by(generator.1)
            .collapsed()
            .with_specificity(if real_build_system {
                SPEC_CONTEXT - 30
            } else {
                SPEC_WEAK + 10
            }),
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::detectors::tests_support::ctx;
    use crate::platform::KnownPaths;

    #[test]
    fn clion_build_directories_match_by_prefix() {
        let env = KnownPaths::empty();
        let detection = CMakeOutput
            .detect(&ctx("cmake-build-debug", Markers::empty(), &env))
            .expect("detection");
        assert_eq!(detection.cleanup, CleanupSafety::Safe);
        assert_eq!(detection.technology, Some(Technology::CMake));
    }

    #[test]
    fn native_build_requires_a_build_script() {
        let env = KnownPaths::empty();
        assert!(NativeBuildDir
            .detect(&ctx("build", Markers::empty(), &env))
            .is_none());
        let detection = NativeBuildDir
            .detect(&ctx("build", Markers::CMAKELISTS, &env))
            .expect("detection");
        assert_eq!(detection.cleanup, CleanupSafety::ProbablySafe);
    }

    #[test]
    fn a_convenience_makefile_does_not_make_a_python_project_native() {
        let env = KnownPaths::empty();
        // `make test` is a near-universal convenience wrapper; it must not turn
        // a Python project's `build/` into a C/C++ explanation.
        let context = ctx("build", Markers::MAKEFILE | Markers::PYPROJECT, &env);
        assert!(NativeBuildDir.detect(&context).is_none());

        // A real native build system still wins, even alongside Python.
        let context = ctx("build", Markers::CMAKELISTS | Markers::PYPROJECT, &env);
        assert!(NativeBuildDir.detect(&context).is_some());
    }

    #[test]
    fn a_makefile_alone_is_only_low_confidence() {
        let env = KnownPaths::empty();
        let weak = NativeBuildDir
            .detect(&ctx("build", Markers::MAKEFILE, &env))
            .expect("detection");
        assert_eq!(weak.confidence, Confidence::Low);

        let strong = NativeBuildDir
            .detect(&ctx("build", Markers::CMAKELISTS, &env))
            .expect("detection");
        assert_eq!(strong.confidence, Confidence::Medium);
        assert!(strong.rank() > weak.rank());
    }

    #[test]
    fn elixir_build_dirs_are_left_to_their_own_detector() {
        let env = KnownPaths::empty();
        let context = ctx("_build", Markers::MAKEFILE | Markers::MIX_EXS, &env);
        assert!(NativeBuildDir.detect(&context).is_none());
    }
}
